### ISSUE TITLE
Repository add-on repository.linuxserver.docker uses old schema definition for the repository extension point! 

### ISSUE THREAD

**Issue by jose1711** [linuxserver/libreelec-addon-repo#101]
Kodi Nexus logs the following in `kodi.log`:
```
error <general>: Repository add-on repository.linuxserver.docker uses old schema definition for the repository extension point! This is no longer supported, please update your addon to use <dir> definitions.
```

**Comment by aptalca** [comment]
Please elaborate, I can't reproduce

**Comment by jose1711** [comment]
Environment: CoreELEC with Kodi 20.2 (Nexus), addon `repository.linuxserver.docker` version 9.0.102.102 installed from LinuxServer.io repository.

Said error keeps appearing in `kodi.log`.

**Comment by aptalca** [comment]
You'll have to ask coreelec to update it on their end. We support libreelec and the repo addon in the libreelec repo was updated a long time ago.

https://github.com/LibreELEC/LibreELEC.tv/commit/526945a9308d4483886013f0dd801220603ab4e7

**Comment by jose1711** [comment]
Thank you.

**Comment by vpeter4** [comment]
CoreELEC also has fixed addon in the repo which works after the update.
