### ISSUE TITLE
Installation of docker.linuxserver.webgrabplus fails on armhf

### ISSUE THREAD

**Issue by mmiesiak** [linuxserver/libreelec-addon-repo#42]
When I try to install docker.linuxserver.webgrabplus addon it fails with following log message in journalctl:

```
Dec 04 22:47:56 LibreELEC sh[3664]: Unable to find image 'lsioarmhf/webgrabplus-armhf:latest' locally
Dec 04 22:48:06 LibreELEC sh[3664]: docker: Error response from daemon: pull access denied for lsioarmhf/webgrabplus-armhf, repository does not exist or may require 'docker login'.
```

Has the image been moved to some other location, i.e. https://hub.docker.com/r/lsioarmhf/webgrabplus/?

**Comment by tobbenb** [comment]
I think it's just a typo so where as the container has always been at lsioarmhf/webgrabplus.
I don't remember how it works in libreelec, but there is no place to edit the repository used I think. 

@aptalca should now though.

**Comment by aptalca** [comment]
Yeah, it was a silly typo.

PR submitted. It will be updated in libreelec repo once merged.
