### ISSUE TITLE
Moving from an existing Nexcloud installation

### ISSUE THREAD

**Issue by the-unknown** [linuxserver/libreelec-addon-repo#54]
Hey, 
I have an existing Nextcloud installation on my Raspberry Pi, setup with raspbian.
I now want to use my RaspberryPi as a LibeElec station and want to move my existing Nextcloud to this Docker version.
The "data" directory is on my external HDD and as database I use the sqlite3 version. 
I'm now having trouble setting up the container to work with sqlite.

I simply copied my existing config.php into the config-folder for this docker and changed the path of the data-folder to match with the new system. 
But when I fireup my browser, I simply get an error 500 and an empty page.

Any idea what to do?

This is my config.php:
(I changed the sensitive data to "xxx")
``` <?php
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' =>
  array (
    0 => 'dyn.xyz.tld',
    1 => 'osmc',
    2 => 'libreelec',
  ),
  'datadirectory' => '/var/media/gigastore/cloud',
  'overwrite.cli.url' => 'https://dyn.xyz.tld/',
  'dbtype' => 'sqlite3',
  'version' => '13.0.0.14',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_xxx',
  'dbpassword' => 'xxx',
  'logtimezone' => 'UTC',
  'installed' => true,
  'maintenance' => false,
  'loglevel' => 2,
  'updater.secret' => 'xxx',
  'theme' => '',
);
```

**Comment by the-unknown** [comment]
I think it has something to do with the Database.... the system cannot open the sqlite database:
```
2019/02/24 20:29:04 [error] 308#308: *8 open() "/config/www/nextcloud/favicon.ico" failed (2: No such file or directory), client: 192.168.0.25, server: _, request: "GET /favicon.ico HTTP/1.1", host: "libreelec"
2019/02/24 20:29:43 [error] 308#308: *11 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [14] unable to open database file in /config/www/nextcloud/lib/private/DB/Connection.php:64
Stack trace:
#0 /config/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(992): OC\DB\Connection->connect()
#1 /config/www/nextcloud/lib/private/DB/Connection.php(216): Doctrine\DBAL\Connection->executeUpdate('PRAGMA read_unc...', Array, Array)
#2 /config/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): OC\DB\Connection->executeUpdate('PRAGMA read_unc...')
#3 /config/www/nextcloud/lib/private/DB/Connection.php(151): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#4 /config/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOSqlite\Driver), Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#5 /con...
PHP message: PHP Fatal error:  Uncaught Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [14] unable to open database file in /config/www/nextcloud/lib/private/DB/Connection.php:64
Stack trace:
#0 /config/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(992): OC\DB\Connection->connect()
#1 /config/www/nextcloud/lib/private/DB/Connection.php(216): Doctrine\DBAL\Connection->executeUpdate('PRAGMA read_unc...', Array, Array)
#2 /config/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): OC\DB\Connection->executeUpdate('PRAGMA read_unc...')
#3 /config/www/nextcloud/lib/private/DB/Connection.php(151): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#4 /config/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOSqlite\Driver), Object(Doctrine\DBA
```

**Comment by j0nnymoe** [comment]
Likely to be a permissions issue. Nextcloud don't actually recommend using the sqlite for production environments.

I would recommend using the backup/restore methods as documented in the nextcloud docs: https://docs.nextcloud.com/server/stable/admin_manual/maintenance/backup.html?highlight=backup

**Comment by the-unknown** [comment]
@j0nnymoe 
I've tested the permission theory by simply changing permissions of the database-file to 777, but getting still the same error. 

backup and restore is not really a way to go for me, as I can't dump an sqlite and restore it into a MariaDB. I can only restore it to an sqlite-db.

**Comment by j0nnymoe** [comment]
No you'd probably need to either migrate to mariadb before you move the install or migrate with sqlite then convert to mariadb.

**Comment by the-unknown** [comment]
@j0nnymoe 
Alright thanks. Will try to convert to MariaDB/MySQL first, backup and the restore into MariaDB Docker

**Comment by the-unknown** [comment]
@j0nnymoe 
I have found the issue:
My /data folder is on an external HDD and by default, the nginx is not able to locate any folders outside of the root-directory. 
As a quick fix, I removed the /data in the root-directory and replaced it with a symlink to the /data on my external HDD. This works now. 
Although I have already migrated from sqlite to MariaDB, the sqlite database works now too.

So in future updates, you might want to add support for external HDD out of the box. As I am a linuxy-user and was able to figure out where to look and fix it myself. However the average LibreElec user, might not be able to figure the same.

**Comment by aptalca** [comment]
Docker containers created through these addons only have access to folders that are mapped in settings. Either map the /data location to the folder the external drive is mapped to on LE, or add additional volume mounts in the extra docker arguments section in addon settings
