### ISSUE TITLE
container not starting on boot

### ISSUE THREAD

**Issue by the-unknown** [linuxserver/libreelec-addon-repo#55]
Hey,

sorry but I have yet another issue:
The nextcloud container does not restart itself on boot/reboot.
It's not listed at all in Portainer.

I have to deactivate and then re-activate it in LibreElec for it to work and show up in portainer.
The MariaDB container however is listed in portainer and starting up on reboot.

**Comment by aptalca** [comment]
Which container?

**Comment by the-unknown** [comment]
Ups, sorry. I did not recognize that this is the "general" repo...

I am talking about the nextcloud container.

**Comment by aptalca** [comment]
after restarting libreelec, check the systemd status with `systemctl status docker.linuxserver.nextcloud` and the logs with `journalctl -u docker.linuxserver.nextcloud`

I just tested a new install and it start fine after a reboot

**Comment by the-unknown** [comment]
`systemctl status docker.linuxserver.nextcloud` gives the following output:

``` ● docker.linuxserver.nextcloud.service - docker.linuxserver.nextcloud container
   Loaded: loaded (/storage/.kodi/addons/docker.linuxserver.nextcloud/system.d/docker.linuxserver.nextcloud.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2019-02-27 05:03:34 CET; 3min 56s ago
  Process: 1796 ExecStart=/bin/sh /storage/.kodi/addons/docker.linuxserver.nextcloud/bin/docker.linuxserver.nextcloud (code=exited, status=125)
 Main PID: 1796 (code=exited, status=125)

Feb 27 05:03:34 LibreELEC systemd[1]: docker.linuxserver.nextcloud.service: Service RestartSec=10s expired, scheduling restart.
Feb 27 05:03:34 LibreELEC systemd[1]: docker.linuxserver.nextcloud.service: Scheduled restart job, restart counter is at 3.
Feb 27 05:03:34 LibreELEC systemd[1]: Stopped docker.linuxserver.nextcloud container.
Feb 27 05:03:34 LibreELEC systemd[1]: docker.linuxserver.nextcloud.service: Start request repeated too quickly.
Feb 27 05:03:34 LibreELEC systemd[1]: docker.linuxserver.nextcloud.service: Failed with result 'exit-code'.
Feb 27 05:03:34 LibreELEC systemd[1]: Failed to start docker.linuxserver.nextcloud container.```

and `journalctl -u docker.linuxserver.nextcloud` says:
```
-- Logs begin at Fri 2018-06-22 13:11:49 CEST, end at Wed 2019-02-27 05:08:54 CET. --
Feb 27 05:02:56 LibreELEC systemd[1]: Started docker.linuxserver.nextcloud container.
Feb 27 05:02:59 LibreELEC sh[681]: mkdir: can't create directory '/storage/.kodi/userdata/addon_data/docker.linuxserver.nextcloud/data': No such file or directory
Feb 27 05:02:59 LibreELEC sh[681]: skipping chown, make sure the folder /storage/.kodi/userdata/addon_data/docker.linuxserver.nextcloud/data is accessible by the user nobody:users (65534:100)
Feb 27 05:03:00 LibreELEC sh[681]: docker: Error response from daemon: error while creating mount source path '/storage/.kodi/userdata/addon_data/docker.linuxserver.nextcloud/data': mkdir /storage/.kodi/userdata
Feb 27 05:03:00 LibreELEC systemd[1]: docker.linuxserver.nextcloud.service: Main process exited, code=exited, status=125/n/a
Feb 27 05:03:00 LibreELEC systemd[1]: docker.linuxserver.nextcloud.service: Failed with result 'exit-code'.
Feb 27 05:03:11 LibreELEC systemd[1]: docker.linuxserver.nextcloud.service: Service RestartSec=10s expired, scheduling restart.
Feb 27 05:03:11 LibreELEC systemd[1]: docker.linuxserver.nextcloud.service: Scheduled restart job, restart counter is at 1.
Feb 27 05:03:11 LibreELEC systemd[1]: Stopped docker.linuxserver.nextcloud container.
Feb 27 05:03:11 LibreELEC systemd[1]: Started docker.linuxserver.nextcloud container.
Feb 27 05:03:11 LibreELEC sh[1644]: mkdir: can't create directory '/storage/.kodi/userdata/addon_data/docker.linuxserver.nextcloud/data': No such file or directory
Feb 27 05:03:11 LibreELEC sh[1644]: skipping chown, make sure the folder /storage/.kodi/userdata/addon_data/docker.linuxserver.nextcloud/data is accessible by the user nobody:users (65534:100)
Feb 27 05:03:12 LibreELEC sh[1644]: docker: Error response from daemon: error while creating mount source path '/storage/.kodi/userdata/addon_data/docker.linuxserver.nextcloud/data': mkdir /storage/.kodi/userdat
Feb 27 05:03:12 LibreELEC systemd[1]: docker.linuxserver.nextcloud.service: Main process exited, code=exited, status=125/n/a
Feb 27 05:03:12 LibreELEC systemd[1]: docker.linuxserver.nextcloud.service: Failed with result 'exit-code'.
Feb 27 05:03:22 LibreELEC systemd[1]: docker.linuxserver.nextcloud.service: Service RestartSec=10s expired, scheduling restart.
Feb 27 05:03:22 LibreELEC systemd[1]: docker.linuxserver.nextcloud.service: Scheduled restart job, restart counter is at 2.
Feb 27 05:03:22 LibreELEC systemd[1]: Stopped docker.linuxserver.nextcloud container.
Feb 27 05:03:22 LibreELEC systemd[1]: Started docker.linuxserver.nextcloud container.
Feb 27 05:03:23 LibreELEC sh[1796]: mkdir: can't create directory '/storage/.kodi/userdata/addon_data/docker.linuxserver.nextcloud/data': No such file or directory
Feb 27 05:03:23 LibreELEC sh[1796]: skipping chown, make sure the folder /storage/.kodi/userdata/addon_data/docker.linuxserver.nextcloud/data is accessible by the user nobody:users (65534:100)
Feb 27 05:03:24 LibreELEC sh[1796]: docker: Error response from daemon: error while creating mount source path '/storage/.kodi/userdata/addon_data/docker.linuxserver.nextcloud/data': mkdir /storage/.kodi/userdat
Feb 27 05:03:24 LibreELEC systemd[1]: docker.linuxserver.nextcloud.service: Main process exited, code=exited, status=125/n/a
Feb 27 05:03:24 LibreELEC systemd[1]: docker.linuxserver.nextcloud.service: Failed with result 'exit-code'.
Feb 27 05:03:34 LibreELEC systemd[1]: docker.linuxserver.nextcloud.service: Service RestartSec=10s expired, scheduling restart.
Feb 27 05:03:34 LibreELEC systemd[1]: docker.linuxserver.nextcloud.service: Scheduled restart job, restart counter is at 3.
Feb 27 05:03:34 LibreELEC systemd[1]: Stopped docker.linuxserver.nextcloud container.
Feb 27 05:03:34 LibreELEC systemd[1]: docker.linuxserver.nextcloud.service: Start request repeated too quickly.
Feb 27 05:03:34 LibreELEC systemd[1]: docker.linuxserver.nextcloud.service: Failed with result 'exit-code'.
Feb 27 05:03:34 LibreELEC systemd[1]: Failed to start docker.linuxserver.nextcloud container.
```

The following line tells me what's wrong:
`Feb 27 05:02:59 LibreELEC sh[681]: mkdir: can't create directory '/storage/.kodi/userdata/addon_data/docker.linuxserver.nextcloud/data': No such file or directory`

I use an external HDD for data. That means "data" is not available until the HDD is mounted.
And that's why the conatiner fails. Is there a way to delay the start of the container at reboot or a way to restart the container on failure?

**Comment by aptalca** [comment]
Yes, the external drive mount is definitely the issue. Nextcloud service is starting before the mount service. It's not easy to customize the nextcloud addon to wait for your mount (as a universal event), however, you should be able to set your mount service to start before the nextcloud service

**Comment by the-unknown** [comment]
I'd need some help on letting the mount-service start before the nextcloud container. I am completely new to LibreElec. Any hint on how to do that?

and a docker has the ability to restart on failure. isn't there a way to do this for the nextcloud container?

**Comment by aptalca** [comment]
Post your current mount service and I'll take a look

**Comment by the-unknown** [comment]
I am using the default configuration of LibreElec. I have not changed anything to its mount-service.

**Comment by aptalca** [comment]
How exactly are you mounting your external drive? I'm not familiar with that process. All I know is it is through a systemd service

**Comment by the-unknown** [comment]
I have no experience with systemd. I know this sounds kinda stupid, but all I do is plugging the external hdd into the usb port (or let's say, it is plugged in permanently). 
I see the "mount" message in Kodi, as soon as the automount is performed. But I don't know where this happens within systemd or how to change the order on boot.

**Comment by the-unknown** [comment]
any idea yet on how to resolve this?

**Comment by aptalca** [comment]
Solved in this thread: https://forum.libreelec.tv/thread/14712-mounting-external-hdd-before-docker-container-starts/
