### ISSUE TITLE
tvheadend config misses device parameter for hwaccel

### ISSUE THREAD

**Issue by jefflessard** [linuxserver/libreelec-addon-repo#60]
kodi config for tvheadend has an option for dvb device but not for a drm device (hwaccel device in ffmpeg).

If one want to specify an hardware acceleration device using the dvb device (D_device setting), it then starts the docker in bridge mode instead of host mode. It will then render hdhomerun unusable.

By adding an additional setting for a hwaccel device, we could then set the renderer device (i.e. /dev/dri/renderD128) and start the docker in host mode.

**Comment by aptalca** [comment]
D_device was only meant for DVB devices

I'm adding a separate field for custom docker arguments. You can put in `--device=/dev/dri` there.

**Comment by jefflessard** [comment]
Great, that will do it. Thank you
