### ISSUE TITLE
Wrong IP on RPI LibreElec

### ISSUE THREAD

**Issue by BoBBer446** [linuxserver/libreelec-addon-repo#69]
Hey, i installed from Repo linuxserer.io and after installation the IP for router or devices is 127.0.0.1 and 172.18.0.1 but thats wron if Adguard runs on RPI.

the IP for DNS is the ip from the RPI

i also have only one ip (the ip from rpi....) and no alternate ip address is configurated. Maybe anyone can fix it :)

**Comment by aptalca** [comment]
I don't follow. What IP are you talking about and what's the issue?

**Comment by BoBBer446** [comment]
I install adguard Home on my Raspberry Pi (192.168.178.39).

But after installation the assistant show as DNS IP 
127.0.0.1
172.18.0.2

But this is wrong because the raspberry Pi is not the router.

In Router I have to set up the ip from the raspberry pi 192.168.178.39 to make it work

**Comment by aptalca** [comment]
The app is unable to determine its lan ip because it's running inside a container in a bridged network.

The instructions we provide in the addon description tell you to use the libreelec ip.

**Comment by BoBBer446** [comment]
Okay, thx. I didn't see it :o
