### ISSUE TITLE
Replace letsencrypt with swag

### ISSUE THREAD

**Issue by evanre** [linuxserver/libreelec-addon-repo#82]
Since the first one is deprecated on official documentation now, I'd appreciate if you guys update it for your libreelec extension. I'd like to suggest a pull request but I'm totally new to all this docker stuff and can't help much.

PS. I don't know how different containers are, if it's just a matter of search-replace for letsencrypt => swag, let me know, I'll make a PR.

**Comment by aptalca** [comment]
swag released: https://github.com/linuxserver/libreelec-addon-repo/pull/83
